### ISSUE TITLE
Coding Guideline - Veejay

### ISSUE THREAD

**Issue by c0ntrol** [c0ntrol/veejay#103]
This is veejay's coding guideline - Its not all like it should be, but that's why this document exists: To write better and consistent code. You are welcome to make suggestions 

**1. Comments**

Doxygen/Javadoc style commenting is OK. Use @-style markup

**2. Code changes**

Indenting corrections should be done before, or after a code update (bugfix, feature enhancement,refactor, etc) but not during. You may break something with manual indenting and styling.

**3. C Style**

Style should be Allman style or K&R (Kerninghan Richie) 

Both styles are currently used in veejay; Preference for K&R is only for short code blocks.

Properly indented code is more important than a specific style.

Normally, Allman style is considered a better choice however, if there are only a few statements in the innerblock, K&R style will make the code more compact and is therefore allowed to be used.

(K&R)

```
for( x = 0; x < width; x ++ ) {
    for( y = 0; y < height; y ++ ) { 
        p = a * b + c;
    }
}
```

(Allman):

```
for ( x = 0; x < width; x ++ )
{
    for( y = 0; y < height; y ++ )
    {
        p = a * b + c;
    }
}
```

Preference for:

```
while( condition != other_condition )
{
     a = a + b * c
     if ( a == 1 ) {
         b = 10
     }
}
```

over:

```
while( condition != other_condition ) {
  a = a + b * c
  if( a == 1 ) { 
      ....
```

Functions (methods) should always be in Allman style:

```
void my_function
{
    /* your code goes here */
}
```

Conditional statements may be in Allman style:

```
if( some_condition != some_other_condition && this != that )
{
    /* logic */
}
else
{
   /* some other logic */
}
```

If a conditional statement is followed by just a single statement, curly braces are not required but the follow up statement must be correctly indented:

```
if( a == b )
    veejay_msg("a equals b");
```

**4. C Features**

If you write code for FX (image filters), please write short and vectorizable loops. 
You are encouraged to pass -ftree-vectorizer-verbose=2 and examine the output

Use

```
for( ... ) {
    a = ( b < 10 ? 255: 0 )
}
```

instead of

```
for( ... )
{
   if( b < 10 )
   {
        a = 255;
   }
   else
   {
        a = 0;
   }
}
```

**5. Naming conventions**
- variables that are only in scope of the file must be static
- functions that are not used outside the scope of the file must be static
- there should be no suffixes or prefixing with _ or any other kind of letter like g_ or m_

**6. Logging**
- printf family is not allowed, use veejay_msg

**7. Editor**

set shiftwidth=4

**Comment by d-j-a-y** [comment]
> C Style

 [indent](https://www.gnu.org/software/indent/manual/) could help.

**Comment by c0ntrol** [comment]
could, if it does not break things - automated things sometimes do

**Comment by c0ntrol** [comment]
inrelevant issue, lets close it
