### ISSUE TITLE
Corrupted/shifted colors with some JPG images

### ISSUE THREAD

**Issue by flv0** [c0ntrol/veejay#125]
I'm loading a jpeg file directly as a commandline parameter and I get corrupted colors. The luminance is correct, but for the colors it looks like a systematic error with actual color values being offset by an increasing amount, resulting in a diagonal line pattern in the color values. Here's a screenshot to illustrate what I mean: [image](http://picpaste.com/pics/window_160715_181554-DNTlNQ5T.1468600967.png). This is the file output for that image containing some format information:

```
Dendrites.jpg: JPEG image data, JFIF standard 1.02, resolution (DPI), density 72x72, segment length 16, Exif Standard: [TIFF image data, little-endian, direntries=15, height=4096, bps=194, compression=none, PhotometricIntepretation=RGB, description=[Parameter-Settings], orientation=upper-left, width=4096], baseline, precision 8, 612x612, frames 3
```

Another JPG opens just fine, with the following file output:

```
cvanbiesen800.jpeg: JPEG image data, JFIF standard 1.01, resolution (DPI), density 300x300, segment length 16, Exif Standard: [TIFF image data, little-endian, direntries=12, description=Shaking your camera while taking a picture is not always a bad , manufacturer=Canon, model=Canon EOS 50D, orientation=upper-left, xresolution=376, yresolution=384, resolutionunit=2, software=GIMP 2.8.14, datetime=2015:08:01 13:43:08], progressive, precision 8, 800x800, frames 3
```

Is there some known problem regarding different JPG formats, or any idea what might be causing this?

**Comment by c0ntrol** [comment]
Hi,

There could be a problem, depending on the resolution veejay is running with ? Perhaps the stride length is not set correctly (padding?) or it scales to a resolution that is not a multiple of 4.  I did see it before, but I never investigated it properly

**Comment by c0ntrol** [comment]
![image](https://cloud.githubusercontent.com/assets/7851900/16896989/41615dc8-4ba4-11e6-86ba-5377c373c72b.png)

**Comment by flv0** [comment]
I checked it with some generated images of different width, and indeed it seems to work correctly only if the width is evenly divisible by 4. Did you mean to imply that the resolution always should be a multiple of 4, so that image data would need to be padded if an image is loaded with width != 4n? Is that some limitation of the jpg format per se or such? Or should it basically work with any image and viewport resolution?

**Comment by c0ntrol** [comment]
Fixed
