### ISSUE TITLE
Record sample : crash when recorded

### ISSUE THREAD

**Issue by d-j-a-y** [c0ntrol/veejay#13]
Veejay record the sample ... and then crash.

I: Recording to [Sample____8_080915_100635-0000.avi]
I: Encoding to MJPEG file [Sample____8_080915_100635-0000.avi]
I: Sample recording started , record 69 frames from sample 8 and dont play new sample
I: Recorded 69 frames
*** Error in `veejay': free(): invalid pointer: 0x00007f1a4c3d4c70 ***
E: No subtitle sequences present, nothing to save
E: No subtitle sequences present, nothing to save
E: No subtitle sequences present, nothing to save
E: No subtitle sequences present, nothing to save
E: No subtitle sequences present, nothing to save
E: No subtitle sequences present, nothing to save
E: No subtitle sequences present, nothing to save
E: No subtitle sequences present, nothing to save
E: No subtitle sequences present, nothing to save
E: No subtitle sequences present, nothing to save
E: No subtitle sequences present, nothing to save
E: No subtitle sequences present, nothing to save
I: Saved EDL to file /home/frijol/.veejay/recovery/recovery_editlist_p18753.edl
W: Saved samplelist to /home/frijol/.veejay/recovery/recovery_samplelist_p18753.sl
W: Saved Editlist to /home/frijol/.veejay/recovery/recovery_editlist_p18753.edl
W: Please report this error to http://groups.google.com/group/veejay-discussion?hl=en
W: Send at least veejay's output and include the command(s) you have used to start it.
W: Also, please consider sending in the recovery files if any have been created.
W: If you compiled it yourself, please include information about your system.
Abandon (core dumped)

**Comment by c0ntrol** [comment]
Fixed

**Comment by d-j-a-y** [comment]
_FIXED !_
