### ISSUE TITLE
FxList : Click+Modifier to add disabled FX

### ISSUE THREAD

**Issue by d-j-a-y** [c0ntrol/veejay#131]
When playing live, this give the ability to prepare the effect's parameters before showing it (and don't be "forced" by default parameters results)

**Comment by c0ntrol** [comment]
OK, this can be done by changing the VIMS event code that adds and/or sets an FX - an extra argument to add the FX in disabled state.

**Comment by d-j-a-y** [comment]
Awesome !

**Comment by d-j-a-y** [comment]
TODO : client doc / man
