### ISSUE TITLE
Libvje / Dices : Right and bottom borders, what to do ?

### ISSUE THREAD

**Issue by d-j-a-y** [c0ntrol/veejay#132]
![veejay-dices-and-borders](https://cloud.githubusercontent.com/assets/2943058/17488788/42fce2e8-5d9b-11e6-9cba-b7fa106e2ecb.png)

Has you can see on the picture, often with low dices per row, borders appear and this "broke" the effect.

Actually i think about two solutions :
- [EASY] Shift the dice left and down by half the space (and fill it with black) 
- [HARDER] Apply the dice anyway on missing part

What do you think ?

**Comment by c0ntrol** [comment]
Just go with the simplest solution,  the other one will slow down processing too much or needs to rewrite large part of the FX
