### ISSUE TITLE
Libvje / common.c : get_pix_func_Y optimize and errors ?

### ISSUE THREAD

**Issue by d-j-a-y** [c0ntrol/veejay#133]
1. [get_pix_func_Y](https://github.com/c0ntrol/veejay/blob/master/veejay-current/veejay-server/libvje/effects/common.c#L490) > replace multiple `if` by `switch` ? 
2.  i guess there is a problem between [pix_type](https://github.com/c0ntrol/veejay/blob/master/veejay-current/veejay-server/libvje/effects/common.c#L492) == 0 and pix_type == [VJ_EFFECT_BLEND_ADDITIVE](https://github.com/c0ntrol/veejay/blob/master/veejay-current/veejay-server/libvje/effects/common.c#L502)  : [VJ_EFFECT_BLEND_ADDITIVE = 0](https://github.com/c0ntrol/veejay/blob/master/veejay-current/veejay-server/libvje/internal.h#L437)

**Comment by c0ntrol** [comment]
1. OK
2. Yes
