### ISSUE TITLE
Sample/Clip from file list

### ISSUE THREAD

**Issue by d-j-a-y** [c0ntrol/veejay#138]
Add a new sample from a file list (ex: a folder)

**Comment by c0ntrol** [comment]
file choosers used are part of standard gtk, not sure how to select directories to add files from. may require a custom file chooser widget. 

for server, this is some work as it will require that EDL files are also automatically loaded when you load all files.

see vj_el_init_with_args in libel/vj-el.c as an example,  and open_video_file

Can be added to VIMS 055 (veejay_edit_addmovie_sample) , veejay/liblavplay.c
