### ISSUE TITLE
Inline asm "fast_cos" , "fast_sqrt" ... seems to be slower!

### ISSUE THREAD

**Issue by d-j-a-y** [c0ntrol/veejay#140]
Profiling (gprof) a [sample code](https://github.com/tcoxon/droste) (looping 15th the call) using the fast_xxx macros i noticed very slower running times.

https://github.com/c0ntrol/veejay/blob/master/veejay-current/veejay-server/libvje/effects/common.h#L98

**Comment by nelburg** [comment]
Where is the sample code and how was it compiled ?

**Comment by d-j-a-y** [comment]
Here is the sample code i have used : [droste.inlineasmtest.tar.gz](https://github.com/c0ntrol/veejay/files/574809/droste.inlineasmtest.tar.gz)

build original droste code with profiling :
`./profbuild.sh xxxx`

build with droste code with inline asm (and profiling):
`./profbuild.sh`

```
$ droste myimage.bmp
$ gprof -b droste gmon.out
```

**Comment by nelburg** [comment]
yes this i have not fixed yet, but you can if you want. the preprocessor macro logic indeed is wrong

**Comment by d-j-a-y** [comment]
> Where is the sample code and how was it compiled ?
fix script build : [droste.inlineasmtest.tar.gz](https://github.com/c0ntrol/veejay/files/581402/droste.inlineasmtest.tar.gz)

**Comment by c0ntrol** [comment]
dropped
