### ISSUE TITLE
3DNow! deprecated, remplace references to "femms" instruction by "emms"

### ISSUE THREAD

**Issue by d-j-a-y** [c0ntrol/veejay#143]
ref :  (AMD64 archi prog manual)[http://amd-dev.wpengine.netdna-cdn.com/wordpress/media/2010/08/26569_APM_v5.pdf] Appendix A page 333

**Comment by nelburg** [comment]
Yes, deprecated since AMD K6 is now a very old CPU, but veejay runs on it.  This instruction should only be used if 3DNOW is also defined (?)

**Comment by d-j-a-y** [comment]
It's not has simple, ... the processor still say i can use 3DNow (by cpuinfo) but the FEMMS instruction has been dropped.

In fact, i think that the femms test  in configure is false 
https://github.com/c0ntrol/veejay/blob/d05f53f54354fdc9bc575df4ac6e0dd6a3f1d966/veejay-current/veejay-server/configure.ac#L482
it check if it's possible to build with a missing instruction (always possible ins't ?)  the problem is running a missing instruction !

**Comment by d-j-a-y** [comment]
For FEMMS, the AMD recommandation is to "Check the status of EDX bit 31 returned by CPUID function 8000_0001h to verify that the processor supports this function" 
http://amd-dev.wpengine.netdna-cdn.com/wordpress/media/2010/08/26569_APM_v5.pdf (viewer - page 48 / book page 18)

**Comment by nelburg** [comment]
Yes, you cannot run with a missing instruction; this will cause an invalid opcode. So, the configure script incorrectly set the ac_cv_flag_3dnow variable ? Then, the test that sets it must be changed, either through what you suggest to run a test application or by other means. I will need to look into this

**Comment by d-j-a-y** [comment]
asm sample of 3dnow feature detection by amd 

```

pushfd                  ; save EFLAGS
pop   eax               ; store EFLAGS in EAX
mov   ebx, eax          ; save in EBX for later testing
xor   eax, 00200000h    ; toggle bit 21
push  eax               ; put to stack
popfd                   ; save changed EAX to EFLAGS
pushfd                  ; push EFLAGS to TOS
pop   eax               ; store EFLAGS in EAX
cmp   eax, ebx          ; see if bit 21 has changed
jz    NO_CPUID          ; if no change, no CPUID


mov   eax, 80000000h    ; query for extended functions
CPUID                   ; get extended function limit
cmp   eax, 80000000h    ; is 8000_0001h supported?
jbe   NO_EXTENDEDMSR    ; if not, 3DNow! tech. not supported

mov   eax, 80000001h    ; setup ext. function 8000_0001h
CPUID                   ; call the function
test  edx, 80000000h    ; test bit 31
jnz   YES_3DNow!        ; 3DNow! technology supported
```
[AMD 3DNow!](http://support.amd.com/TechDocs/21928.pdf) ,  page 13 (reader) / 3 (document)

**Comment by d-j-a-y** [comment]
About runtime detection:
I have created a new branch with an update of aclib (from transcode software).
This give the ability to detect new instructions sets:
* x86: SSSE3 instructions
* x86: SSE4.1 instructions
* x86: SSE4.2 instructions (Intel) 
* x86: SSE4a instructions (AMD)
* x86: SSE5 instructions (AMD)
 
https://github.com/d-j-a-y/veejay/tree/djay_aclib_update

**Comment by nelburg** [comment]
Does aclib also detect the 3DNow instruction set ? libavutil from ffmpeg also provides runtime detection of cpu capabilities: https://www.ffmpeg.org/doxygen/2.6/cpu_8c.html, which would be preferable to aclib

**Comment by d-j-a-y** [comment]
>Does aclib also detect the 3DNow instruction set ?

Yes [-->](https://github.com/d-j-a-y/veejay/blob/514d838dc363f26a47132e9dbd99dd4001c2ebcc/veejay-current/veejay-server/thirdparty/aclib/accore.c#L291) . The aclib and libav/ffmpeg cpu 3dnow! detection procedure seems to be similar , and conform to [AMD's recommandation](https://github.com/c0ntrol/veejay/issues/143#issuecomment-266093154).

For the runtime detection point of view, do think to function pointers ?

**Comment by d-j-a-y** [comment]
Aclib test result on an AMD bulldozer -15th generation- (who crash at runtime because 3dNow detected during configure)
`I: CPU flags: sse5 sse4a sse42 sse41 ssse3 sse3 sse2 sse mmxext mmx cmove asm`

So the updated aclib runtime test seems to be valid and could be also used.

**Comment by c0ntrol** [comment]
dropped femms, need new issue for detection of cpu run time capabilities
function pointers will be needed yes
if choosen for aclib, it must be added to thirdparty/ directory
