### ISSUE TITLE
Libvje / common.c & magicovelays.c blend method factorization 

### ISSUE THREAD

**Issue by d-j-a-y** [c0ntrol/veejay#145]
Seems code is duplicated here and there.

From magicoverlays call the according common.c blend implementation, checking the best algo from both : magicoverlays blends code seems to be better (pixel_y_low and high test avoiding divide by 0)

Idem for magicalalphaoverlays.c ?

**Comment by c0ntrol** [comment]
Yes, but for me not necessary

In fact, some blend modes that are duplicate may in fact be different and will need to be reviewed

Also, the methods in common are different as these are governed by a function pointer mechanism, which is slower (?) then the implementation in magicalphaoverlays (a function call per pixel vs. operations on data directly)

**Comment by c0ntrol** [comment]
closing issue, no priority
