### ISSUE TITLE
Libvje / Ripple : out of palette color regions

### ISSUE THREAD

**Issue by d-j-a-y** [c0ntrol/veejay#146]
When waves (_w), ampli (_a) and attenuation (_att) near minimum values, visual artefacts appears : out of palette color regions.
![ripple_outofpalette](https://cloud.githubusercontent.com/assets/2943058/21453079/0eeead10-c90c-11e6-9c03-54014d78500e.png) 

> The green color is not present in original image.

**Comment by c0ntrol** [comment]
fixed
