### ISSUE TITLE
dead lock : on "apply key frame" with very long sample 

### ISSUE THREAD

**Issue by d-j-a-y** [c0ntrol/veejay#150]
* load and play a long clip (mine was > 22min)
* add and effect
* FX Anim panel, draw curve 
* click [OK] (apply key frame) - Dead lock

**Comment by nelburg** [comment]
known issue, the problem is that in this case, the entire keyframe datastructure is calculated and transported to reloaded (33000 x sizeof(key_frame_structure)). so , this implementation is quite naive. did you see where the deadlock happened in gdb ?

**Comment by c0ntrol** [comment]
Fixed

**Comment by d-j-a-y** [comment]
can't want to test !!!! thank's for fixing!
