### ISSUE TITLE
./configure fails for veejay-client:  configure: error: Cannot find veejay 1.5.60 or later

### ISSUE THREAD

**Issue by tkoham** [c0ntrol/veejay#155]
I have compiled and installed veejay-server, but when I try to build veejay-client, ./configure fails saying it can't be found.

Is there a flax I can pass or an `export` env variable I can do to work around this?

**Comment by d-j-a-y** [comment]
did you installed it system wise or in a specific location (--prefix) ?

**Comment by c0ntrol** [comment]
Is the problem still there ?

Normally, if the system does not immediately pick up the veejay libraries you can run ldconfig to have the library cache updated

If you installed veejay server to a custom location, please make sure that the library path is listed in ld.conf
