### ISSUE TITLE
Feature:  Video splitter

### ISSUE THREAD

**Issue by c0ntrol** [c0ntrol/veejay#16]
Split current veejay output into multiple "video streams" and push them to other veejay instances through shared memory and/or networking. 

* extend VIMS with method to retrieve: width,height,shm key,pixel format
* extend veejay client routines to fetch remote properties
* extend veejay client routines to fetch remote live-inputs
* extend projection mapping setup
* add video splitter
* each screen maps to a remote or local running veejay (but not itself)
* unlimited screens
* non invasive on current running veejay

**Comment by c0ntrol** [comment]
Done

**Comment by c0ntrol** [comment]
![multitrack_splitscreens](https://cloud.githubusercontent.com/assets/7851900/10651638/103e08ee-7851-11e5-861f-0bb5a21ccf0a.png)
![splitscreen](https://cloud.githubusercontent.com/assets/7851900/10651640/18229d68-7851-11e5-99ae-808bd2981a19.png)

**Comment by d-j-a-y** [comment]
FaNtasTIcaLLy CRazy ! 
I can't wait to test !

**Comment by c0ntrol** [comment]
Its only a simple splitter! 

http://www.piwall.co.uk/ has a separate library to calculate the video tiles. If each veejay would have the same video, then each one can render its own part instead of having the master veejay distribute the image parts to render (which it does now)

what is needed for this is:
* fix multicast network i/o
* pwlibs from piwall
* VIMS message to negotiate

**Comment by d-j-a-y** [comment]
Tested with success following video-wall doc from [here](https://github.com/c0ntrol/veejay/blob/master/veejay-current/veejay-server/doc/video-wall.md)

de3548acba155072d0c967f8fa274b8b890cbf58
