### ISSUE TITLE
sayVIMS : '?' broken

### ISSUE THREAD

**Issue by d-j-a-y** [c0ntrol/veejay#188]
> Typing '?' followed by pressing `ENTER` gives the list of command below:
> vi [file]           Open video4linux device
> fi [file]           Open Y4M stream for input
> fo [file]           Open Y4M stream for output
> av [file]           Open (almost any) video file using FFmpeg
> mc [address] [port] Open a multicast UDP video stream
> pr [hostname][port] Open a unicast TCP video stream
> cl [file]           Load cliplist from file
> ...

(_veejay-HOWTO_)

**Comment by c0ntrol** [comment]
I think, the behaviour has changed and that it partly contains outdated features. Keep or remove the built-in interpreter?

**Comment by d-j-a-y** [comment]
I did'nt quickly found any trace of code (from sayVIMS.c & vj-event.c ) related to this feature, so, I think that can be safely remove from the doc now ....

**Comment by d-j-a-y** [comment]
cab734d
