### ISSUE TITLE
Utils missing yuv2rawdv , rawdv2yuv and any2yuv  ...

### ISSUE THREAD

**Issue by d-j-a-y** [c0ntrol/veejay#189]
> 4.6 Other utilities
>
> Currently there are 4 extra utilities yuv2rawdv , rawdv2yuv , sayVIMS and any2yuv

veejay-howto

if removed, any idea on how to rewrite that part [46-other-utilities](https://github.com/d-j-a-y/veejay/blob/djay_help_update/veejay-current/veejay-server/doc/veejay-HOWTO.md#46-other-utilities) ?

**Comment by c0ntrol** [comment]
That's okay, simple remove it, there is nothing to re-write

On using sayVIMS, we can explain that you can get the full list of VIMS commands by running "veejay -u" and then, we show some examples like "echo 600:;|sayVIMS" and that's enough

**Comment by d-j-a-y** [comment]
cab734d
