### ISSUE TITLE
veejay -V (multicast frame sender) broken/removed ? 

### ISSUE THREAD

**Issue by d-j-a-y** [c0ntrol/veejay#190]
( still a reference here in getops https://github.com/c0ntrol/veejay/blob/master/veejay-current/veejay-server/veejay/veejay.c#L629 )

if removed, how to rewrite that part [453-network](https://github.com/d-j-a-y/veejay/blob/djay_help_update/veejay-current/veejay-server/doc/veejay-HOWTO.md#453-network) ?

**Comment by c0ntrol** [comment]
I think, only the commandline option was removed, veejay can still do multicast frame sending - There is a VIMS message to enable/disable this

**Comment by d-j-a-y** [comment]
The only VIMS multicast related seems to be _246    'Open UDP multicast as new input stream'_ but I'm sure you are thinking to something else ....  isn't it ?

**Comment by d-j-a-y** [comment]
> There is a VIMS message to enable/disable this

In fact VIMS 22 & 23 "doesn't work" if veejay was not started with -V option 
_E: start veejay in multicast mode (see -V commandline option)_ [vj-event.c L9106](https://github.com/c0ntrol/veejay/blob/master/veejay-current/veejay-server/veejay/vj-event.c#L9106)

**Comment by c0ntrol** [comment]
Yes, this is correct. Veejay needs a multicast address to broadcast on. We can change this, so that the user passes the broadcast address to the VIMS command, e.g: 22:224.0.0.0;

**Comment by c0ntrol** [comment]
Continue with #233, close issue
