### ISSUE TITLE
Transition (FX Fade) - original source to completed chain : default chrominance pb ?

### ISSUE THREAD

**Issue by d-j-a-y** [c0ntrol/veejay#210]
* On first run luminance ok + green chromiance (1)
![veejaty-issue-210-01](https://user-images.githubusercontent.com/2943058/59092290-b7e8bf80-8900-11e9-968c-6b48b04e54a6.jpeg)

* When run after "selected entry (before fx) to complete chain" : static image + strange lines (2)
![veejaty-issue-210-02](https://user-images.githubusercontent.com/2943058/59092291-b7e8bf80-8900-11e9-80d5-ea8609cffdca.jpeg)
(i have drawn white lines to indicate the strange lines)

**How to reproduce** : 

1.
* start veejay and play a sample
* add an effect (using geometrics fx it's easier to see)
* select "original source to completed chain" fade type
* Fade in (or Fade out) ----> **GREEN**

2.
* start veejay and play a sample
* add an effect (using geometrics fx it's easier to see)
* Fade in (or Fade out) using default fade type (selected entry (before fx) to complete chain)
* select "original source to completed chain" fade type
* Fade in (or Fade out) ----> **Strange Lines**

**Comment by c0ntrol** [comment]
fixed
