### ISSUE TITLE
psp platform : drop support or config with sdl1.2 ?

### ISSUE THREAD

**Issue by d-j-a-y** [c0ntrol/veejay#221]
Sdl2 actually doesn't support playstation platform.

> Dead platforms
> 
> We ripped out a bunch of old platforms, like OS/2 and Mac OS 9. It would be easier to list the ones we still support: Windows (XP and later), Linux, Mac OS X, iOS, Android. In SDL tradition, there are others on the periphery that work but aren't heavily supported, like Haiku and Sony PSP. We'll add any platform that someone sends patches for, but it seemed like it was time to say goodbye to some old friends when moving to the new version.
> --------------------http://wiki.libsdl.org/MigrationGuide------------

**Comment by c0ntrol** [comment]
veejay has no explicit support for PS/2, there is only a section in the configure script that detects compilation on PS/2. 
Also, you can compile veejay-server without SDL2 (it is only the configure script that gives a fatal error when SDL2 is missing)
Finally, SDL1.2.x has rotten bits

Thus, nothing needs to be done.
