### ISSUE TITLE
lvdgmic : libgmic-dev check missing in configure (gmic.h)

### ISSUE THREAD

**Issue by d-j-a-y** [c0ntrol/veejay#222]

**Comment by c0ntrol** [comment]
libgmic-dev is the name of the development package,

in configure.ac, there is a AC_CHECK_HEADERS that checks for gmic.c and the Makefile.am hardcodes linking the gmic library with -llibgmic ; This works as long as the library and headers are installed,
Usually, when gmic.h is there, the library is also there. This is the assumption the build script makes
GMIC doesn't provide a pkgconfig file, so using PKG_CHECK_MODULES will be useless. Ofcourse, we could fiddle with AC_CHECK_LIB and come up with something that works, so the hardcoded -llibgmic can be replaced for a variable.

Is your gmic installed in a custom location ?

**Comment by d-j-a-y** [comment]
the problem was between the chair and keyboard....
