### ISSUE TITLE
Reloaded disconnect saving curve when server is overloaded, and long sample ?

### ISSUE THREAD

**Issue by d-j-a-y** [c0ntrol/veejay#236]
Using a 00:02:37.40 sample 
_(no issue with a 5s sample long for example)_

```
E: Failed to connect to command port
[Thread 0x7fffdca00700 (LWP 19607) exited]
[Thread 0x7fffdd201700 (LWP 19606) exited]
[Thread 0x7fffd7fff700 (LWP 19608) exited]
[New Thread 0x7fffd7fff700 (LWP 19615)]
[Thread 0x7fffd7fff700 (LWP 19615) exited]
E: Error while receiving from network: Connexion ré-initialisée par le correspondant
```
* start veejay with a sample
* create some intensive fx chain (yes GMICs ... by the way Light Patch is nice, and i'm sure could be easily port native ;-)
* open reloaded
* fx anim panel, save ---> disconnect

my fx chain was (anim on chromiun)
```
I: 00 | 510 | on  |LVD G'MIC/GREYs Light Patch 2x2 {P0 = 2 P1 = 6 P2 = 400 }
I: 01 | 650 | on  |frei0r Sobel 2x2 {}
I: 04            on  | Chromium
```

**Comment by c0ntrol** [comment]
How long was the sample ? Probably there's is a hangup due to corrupted/unexpected data

**Comment by d-j-a-y** [comment]
Duration: 00:02:37.40

and yes, sample duration affect issue. i'have tested with a 5s sample, work like a charm.

**Comment by c0ntrol** [comment]
Cool, that narrows down the problem :)

**Comment by c0ntrol** [comment]
Fixed this veejay-core
