### ISSUE TITLE
Black is not black ! (colorspace pb)

### ISSUE THREAD

**Issue by d-j-a-y** [c0ntrol/veejay#240]
$ veejay -d

![blackIsNOt](https://user-images.githubusercontent.com/2943058/60643079-7bd24d00-9e21-11e9-96ab-dfd584fcfe3f.png)

From top to down : veejay / black / white.

(this appear NOT only in dummy mode sample also, maybe stream....)

**Comment by c0ntrol** [comment]
How exactly to reproduce this ?

**Comment by d-j-a-y** [comment]
libsdl2-dev    2.0.5+dfsg1- amd64 

>How exactly to reproduce this ?

$ veejay -d

>what driver is SDL2 using for display output ?

both SDL_VIDEODRIVER / SDL_VIDEO_GL_DRIVER are blank. So should use default  "X11"  https://wiki.libsdl.org/FAQUsingSDL  - Another way to get sdl2 driver info ?

> when black is not black, can you look at the pixel data and see what values are in the Y channel ?
(break on dummy_apply)
this would confirm that the issue is later in the chain

Sometime i can see black then grey output at first start.
dummy_apply from libvje ? don't break there at startup ?  

__NOTA__ : In previous screenshot, upper part is grey , this is veejay sdl output. Black and white part are shown has references!

**Comment by c0ntrol** [comment]
Veejay should output SDL driver (https://github.com/c0ntrol/veejay/blob/9c430b3999bbf00648d7199bba30a2b2d46955de/veejay-current/veejay-server/veejay/vj-sdl.c#L191)

I'll put in a few debug statements tomorrow 

o/

**Comment by d-j-a-y** [comment]
```
I: Using output driver SDL
I: Using SDL driver opengl
D: The renderer uses hardware acceleration: yes
D: Present is synchronized with the refresh rate: yes
D: Set VEEJAY_SDL_DRIVER to select another driver
D: SDL Output dimensions: 720 x 576
D: Grabbed mouse focus
D: Initializing the threading system
D: Starting software playback thread
I: Pinned playback timer thread to cpu #1
D: Started playback
I: Using default scheduling for process 3352

```

**Comment by c0ntrol** [comment]
Thanks,

I have pushed some fixes:

- RGB color space conversion for CCIR601 was incorrect (affects dummy frame)
- Set SDL yuv conversion mode (CCIR601 / JPEG)
- Fixed handling of CCIR601 and JPEG yuv ranges

If you --enable-strict during configure, veejay will log what color space conversion it initializes

**Comment by d-j-a-y** [comment]
SDL from version 2.0.8 has support for full range YUV and specifying
BT601/BT709 color space for YUV->RGB conversion. 

debian old-stable 2.0.5 , debian stable aka buster (released this yesterday) 2.0.9 !

**Comment by c0ntrol** [comment]
Nice, but does it work ? 🤣

**Comment by d-j-a-y** [comment]
system fuckup after upgrade... ! i saw you laughing hidden behind your vm .... ;-)

**Comment by c0ntrol** [comment]
🤣 ⛑ 

good luck fixing failed upgrade :)

i remember i still have a partition with a failed upgrade from ubuntu 12 to 14, something with properiety graphic drivers
But yea, VM -> restore snapshot

**Comment by d-j-a-y** [comment]
from Fedora i can say, now black is black ...  !

**Comment by c0ntrol** [comment]
That's cool, let's hope its like that on every distro!
