### ISSUE TITLE
Veejay - Image Effect ChameleonTV (EffectTV) , only on upper part !

### ISSUE THREAD

**Issue by d-j-a-y** [c0ntrol/veejay#25]
When adding the "Image Effect ChameleonTV (EffectTV)" , the effect is only applied on the upper part of the image (half top of the image)

![veejay-issue25-chameleon_on_upper_part](https://cloud.githubusercontent.com/assets/2943058/10563948/70bcbb98-759f-11e5-9fc3-4bcd327ef830.png)

**Comment by c0ntrol** [comment]
verified

**Comment by d-j-a-y** [comment]
verified : fixed
