### ISSUE TITLE
Quick jumps into video samples 

### ISSUE THREAD

**Issue by d-j-a-y** [c0ntrol/veejay#255]
Using VIMS_VIDEO_SET_FRAME (?) for sample jump, and map
new UI and KEYCODE to jump into range 0% to 90% using keys like [0] to [9]

Bonus : The exact destination (not always strict decade) of the jumps could be fixed manually  (UI / VIMS)  to have the ability to choose the perfect frame for each of the 10 quick jumps.

(you can test the fun of this feature using [0] -> [9] when playing youtube videos)

**Comment by c0ntrol** [comment]
adding this to veejay-server side

**Comment by c0ntrol** [comment]
done

**Comment by c0ntrol** [comment]
For bonus: this is UI logic only using VIMS_VIDEO_SET_FRAME. Somehow .. the user would probably want to save this after setting the positions for the perfect jumps

**Comment by d-j-a-y** [comment]
So awesome!
it's really a must have for performing! is'nt it ?

Next step; buffering the streams and have to same xperience in the stream buffer! :-0

**Comment by c0ntrol** [comment]
Buffering the streams is an option; It will either take diskspace or RAM. What should be the default behaviour here ? Always buffer the stream ?

**Comment by d-j-a-y** [comment]
>Buffering the streams is an option; It will either take diskspace or RAM. What should be the default behaviour here ? Always buffer the stream ?

I think, 
* disabled by default
* command line option
* ram or file (ssd should be quick enought?) has advanced option

**Comment by c0ntrol** [comment]
I think a commandline switch is too much trouble for the user and having it disabled by default will have only veejay experts use it

how about:

**reloaded**: new spinbutton with label "Memory buffer size in frames"  and a label that prints the timecode. Lets call this Q
**reloaded**: new switch "Play frames from memory"

The memory buffer would simply dump the frames to disk (SSD), uncompressed.

While the memory buffer is played back, each frame played is replaced for a new incoming frame, so the stream is always at most X frames behind.

A sample can be used here too; each time Q frames are played, we can update the edit decision list and load the new video sequence. Then, we update the the start/end positions and we can keep doing this, while in the background, the stream is still beeing recorded. What do you think?

**Comment by c0ntrol** [comment]
Record 50 frames from stream #4 and append it to sample 1 
`
echo "228:4 50 0 1;" | sayVIMS
`

To summarize:
**reloaded** The sample panel has a new frame "Live feed buffer"
**reloaded** The sample panel has a spinbox with the label "Link to stream"
**reloaded** The sample panel has a spinbox with the label "Frames to buffer from stream" (Q)
**reloaded** The sample panel has a switch "Buffered stream playback" 

When "buffered stream playback" is enabled, the offline recorder keeps recording video files of Q frames in length from stream "Link to stream" and appends them to the sample's edit decision list. Each time, the start and end positions of the sample are updated. When "buffered stream playback" is disabled, the offline recorder stops and the sample keeps looping based on current data.

**Comment by c0ntrol** [comment]
done

**Comment by d-j-a-y** [comment]
Interesting approach ;-) 

But I think that the user experience needto be polished.

For me it's an ux error to be obliged to setup a sample to play with streams. This is revelant from coding logics, but not
from the user side.

ie: I'm playing a stream, I activate the buffer because I know that i will use it. From user logic I search for this feature directly in the stream's properties I'm playing. 

**_Related task_** Maybe it's the time to create panels for the stream ? :
* Record to disk 
* Transitions
* Quick Jump controls  (Buffered stream controls) <----- This panel could also be added to samples to parameters the jumps destination
* Stream properties (camera control / generator parameters / ..)

**Comment by c0ntrol** [comment]
The related task you can create, that's fine with me!

**Comment by d-j-a-y** [comment]
>  From a technical point of view; The stream would need to create (or select) an empty sample and then append the video recordings to it. While the stream is active, there is no trickplay possible. So, it has to switch to the newly created sample to play the buffers.

When stream buffer is activated, 10 hidden samples linked to the stream are created and filled.
Could the be a kind of rollover in the name, to fill the 10 samples each Q.
When the user hit [1-9] a buffered sample is played. [0] and [F1 - F12] corresping to the stream live

In did, this logic could hurt veejay heart ....
