### ISSUE TITLE
[SOLVED] Required dependencies for Ubuntu 14.04

### ISSUE THREAD

**Issue by zenny** [c0ntrol/veejay#26]
configure:  Required dependencies:
configure:   - POSIX Threads (pthread)       : true
configure:   - FFmpeg/AV AVFormat            : true 
configure:   - FFmpeg/AV AVCodec             : true 
configure:   - FFmpeg/AV Swscaler            : true 
configure:   - FFmpeg/AV AVUtil              : true 
configure:   - SDL support                   : true
configure:   - SDL on-screen-logging         : false
configure:   - Freetype support              : true
configure:   - XML c library for Gnome       : true
configure:   - JPEG support                  : true 
configure:   - GDK Pixbuf support            : true
configure:  Optional dependencies
configure:   - DirectFB support              : true
configure:   - libDV (digital video) support : false 
configure:   - QuickTime support             : false 
configure:   - Jack Audio Connection Kit     : true
configure:   - Liblo OSC client              : false
configure:   - V4L2 (default)                : true
configure:   - V4L1 (obsolete)               : false
configure:   - libunwind                     : true
configure:   - QR code support (libqrencode) : false

Among the required dependencies, SDL on-screen-logging cannot be enabled even if the libsdl libraries are installed:

$ dpkg -l | grep ii | grep libsdl
ii  libsdl-image1.2:amd64                       1.2.12-5build2                                              amd64        Image loading library for Simple DirectMedia Layer 1.2, libraries
ii  libsdl1.2-dev                               1.2.15-8ubuntu1.1                                           amd64        Simple DirectMedia Layer development files
ii  libsdl1.2debian:amd64                       1.2.15-8ubuntu1.1                                           amd64        Simple DirectMedia Layer
ii  libsdl2-2.0-0:amd64                         2.0.2+dfsg1-3ubuntu1.1                                      amd64        Simple DirectMedia Layer
ii  libsdl2-dev                                 2.0.2+dfsg1-3ubuntu1.1                                      amd64        Simple DirectMedia Layer development files

Did I miss something? Thanks!

**Comment by c0ntrol** [comment]
Yes libsdl-ttf2.0-dev

**Comment by zenny** [comment]
Thanks, that was it!
