### ISSUE TITLE
'veejay/Makefile.in' not found

### ISSUE THREAD

**Issue by gui-lux** [c0ntrol/veejay#267]
Hi all,

when compiling veejay-server / ubuntu 20.04, this happens at autogen.sh stage : 

autoreconf: Entering directory `.'
autoreconf: configure.ac: not using Gettext
autoreconf: running: aclocal -I m4 --force -I m4 
autoreconf: configure.ac: tracing
autoreconf: running: libtoolize --copy --force
libtoolize: putting auxiliary files in '.'.
libtoolize: copying file './ltmain.sh'
libtoolize: putting macros in AC_CONFIG_MACRO_DIRS, 'm4'.
libtoolize: copying file 'm4/libtool.m4'
libtoolize: copying file 'm4/ltoptions.m4'
libtoolize: copying file 'm4/ltsugar.m4'
libtoolize: copying file 'm4/ltversion.m4'
libtoolize: copying file 'm4/lt~obsolete.m4'
autoreconf: running: /usr/bin/autoconf --include=m4 --force
autoreconf: running: /usr/bin/autoheader --include=m4 --force
autoreconf: running: automake --add-missing --copy --force-missing
configure.ac:113: installing './compile'
configure.ac:19: installing './missing'
configure.ac:1111: error: required file 'veejay/Makefile.in' not found
libel/Makefile.am: installing './depcomp'
autoreconf: automake failed with exit status: 1

Many thanks for your help
++

**Comment by d-j-a-y** [comment]
Hi
Firstly to be sure of a correct build process:
* Where point (commit) the source code you want to build? (often better to build last source code)
* Did you build and install veejay-core before veejay-server ? ([install procedure](https://github.com/c0ntrol/veejay/blob/master/veejay-current/veejay-server/doc/HOWTO.compile.md) have change few months ago) 
* ....

**Comment by c0ntrol** [comment]
It was missing veejay/Makefile.am , this is fixed now.
