### ISSUE TITLE
Verify BigDesktop/TwinView setup

### ISSUE THREAD

**Issue by c0ntrol** [c0ntrol/veejay#27]
Verify SDL video window setup for BigDesktop/TwinView

VEEJAY_DESKTOP_GEOMETRY WxH+XxY
VEEJAY_VIDEO_POSITION XxY
VEEJAY_VIDEO_SIZE WxH

example:
`export VEEJAY_DESKTOP_GEOMETRY=1980x1080+0x0`

VEEJAY_DESKTOP_GEOMETRY : Size of your screen and position
VEEJAY_VIDEO_POSITION: Position in screen
VEEJAY_VIDEO_SIZE: Size of video in scren

**Comment by zenny** [comment]
This works fine with a single monitor (not in twin-view mode). Yay!

Tried with:

export VEEJAY_DESKTOP_GEOMETRY=1980x1080+0x0
export VEEJAY_VIDEO_POSITION=0x0
export VEEJAY_VIDEO_SIZE=1280x720

Check with twinview with dualhead graphical card.
