### ISSUE TITLE
New issues of lvd crop and scale

### ISSUE THREAD

**Issue by zenny** [c0ntrol/veejay#35]
LVDcrop and scale was working fine though not as desired (crop and
scale should be separate entities like in the frei0r.scale0tilt
filter, but now when one crops a video it goes out of proportions (see
attached screencapture), but works fine with a picture.

**Comment by d-j-a-y** [comment]
> see attached screencapture

missing ?

**Comment by zenny** [comment]
Video cannot be uploaded here afaik (see screenshot). So trying to upload to vid.me (hope it works).

1. On times, the samplelist loads with all samples as solid black samples.

2. LVDcropNresize only crops on the right, even though left parameters were elevated.

3. LVDcrop filter is desired to replace the crop area with transparency, not solid black.

**Comment by c0ntrol** [comment]
> On times, the samplelist loads with all samples as solid black samples.

On those times, did you start veejay from a different directory ? Normally it looks in the current working directory for EDL files saved with the samplelist. 

LVD crop/scale is not correctly implemented, I may remove it or rename it to what it actually became 

A) Crop the video (black what is cropped out)
B) Alpha switch: create mask of cropped area, 0 is invisible, 255 is entirely visible and show original video (instead of black)

If you use this on Sample 2, you can play Sample 1 with the travel matte applied to Sample 2

**Comment by zenny** [comment]
Despite starting veejay from the same directory where files are located, it still behaves randomly. Some thumbnails in the sample are solid black (that of video) and the thumbnails of the picture are alright). See screenshot at: http://picpaste.com/APVzCFBK.png

**Comment by zenny** [comment]
> LVD crop: Perhaps you are looking for a switch ?
> off) Crop the video (black what is cropped out)
> on) Alpha switch: create mask of cropped area, 0 is invisible, 255 is entirely visible and show original video (instead of black)

Yep that would be nicer.

**Comment by zenny** [comment]
> If you use this on Sample 2, you can play Sample 1 with the travel matte applied to Sample 2

The results are: (without crop): http://imgur.com/OZIED1j
(with crop): http://imgur.com/nzjSNJW

And when I tried to cut and copy the filter (alpha-travel matte), reloaded crashed.

**Comment by c0ntrol** [comment]
done:
scale0tilt was added as a livido plugin (YUV space + alpha) 

still todo:
crop with alpha switch


usage:
Sample A:
0: Add Alpha (Set from Image, Fill, Black/White Mask by Threshold etc)
1: LVD scale0tilt with sample B 

Sample B:
0: Add Alpha (Set from Image, ... )

**Comment by zenny** [comment]
> usage:
> Sample A:
> 0: Add Alpha (Set from Image, Fill, Black/White Mask by Threshold etc)
> 1: LVD scale0tilt with sample B

> Sample B:
> 0: Add Alpha (Set from Image, ... )

Veejay updated to latest commit:

The result is as shown in the screenshots below, does not work as expected.

Folder structure: http://picpaste.com/Wsn7r57u.png
The background picture with filters: http://picpaste.com/9Ad8Ea2s.png
Final Result with foreground filters list: http://picpaste.com/VSgjE64T.png

**Comment by c0ntrol** [comment]
There have been a few fixes! A step at a time

The FX you used in the chain I will review, but its possible you didnt enable the Alpha parameters on some FX ? 

![sources](https://cloud.githubusercontent.com/assets/7851900/10955728/5796450c-8356-11e5-9666-8720c55eec21.png)
![step1](https://cloud.githubusercontent.com/assets/7851900/10955733/579d00c2-8356-11e5-8efd-a9869c4ed82a.png)
![step2](https://cloud.githubusercontent.com/assets/7851900/10955729/579a2348-8356-11e5-99fa-537086323d01.png)
![step3](https://cloud.githubusercontent.com/assets/7851900/10955731/579b1668-8356-11e5-92e5-d1c0e2c764b5.png)
![step4](https://cloud.githubusercontent.com/assets/7851900/10955730/579b1424-8356-11e5-9950-8ae77dad7365.png)
![step5](https://cloud.githubusercontent.com/assets/7851900/10955732/579ba25e-8356-11e5-9199-dd9730167406.png)
![step5b](https://cloud.githubusercontent.com/assets/7851900/10955734/57ad83fc-8356-11e5-9517-bc076c67321b.png)

**Comment by zenny** [comment]
Hi Niels,

Though followed the same steps as you desribed earlier, yet I am not
getting the same result as you do. See screenshots attached. :(

Wbr,
/z

**Comment by c0ntrol** [comment]
Your Luma Key effect is using Sample 1 (the same as the playing sample) as a mixing source. You can double-click another sample in the "mixing sources" tab

**Comment by c0ntrol** [comment]
Keep issue open until
* default parameters are fixed in LVD scale0tilt
* LVD Crop Stretch

LVD Crop should be OK (invert selection parameter was added)

**Comment by c0ntrol** [comment]
* default parameters zero for scale0tilt (requires enchancement to livido to support normalized parameter values since values are dependent on width/height of video, affects scale X/Y, tilt X/y parameters)
* crop stretch is correct, it simply scales the image to full size after cropping without keeping aspect ratio
