### ISSUE TITLE
Ubuntu 14.04.3 QR code support (libqrencode) : false

### ISSUE THREAD

**Issue by zenny** [c0ntrol/veejay#37]
Even with libqrencode-dev package installed (see below), veejay server configure says that qrcode support is not enabled.

# configure:   - QR code support (libqrencode) : false

$ dpkg -l | grep ii | grep libqrencode
# ii  libqrencode-dev                             3.4.2-1                                                     amd64        QR Code encoding library -- development
ii  libqrencode3:amd64                          3.4.2-1                                                     amd64        QR Code encoding library

**Comment by c0ntrol** [comment]
You can use github formatting to indent what you paste :) 

A fix is 18221ad1fba9a1ee57ce224ffd5048f3ef2c5fbd but you will have to start from a clean source tree (re-run autoconf or ./autogen.sh)
