### ISSUE TITLE
Fix automake warnings

### ISSUE THREAD

**Issue by flvi0** [c0ntrol/veejay#4]
with automake-1.15 on Gentoo I get a lot of deprecation warnings from automake/autogen.sh:

bio2jack/Makefile.am:2: warning: 'INCLUDES' is the old name for 'AM_CPPFLAGS' (or '*_CPPFLAGS')

libsubsample/Makefile.am:2: warning: 'CFLAGS' is a user variable, you should not override it;
libsubsample/Makefile.am:2: use 'AM_CFLAGS' instead

libvje/Makefile.am:55: warning: source file 'effects/common.c' is in a subdirectory,
libvje/Makefile.am:55: but option 'subdir-objects' is disabled

automake-1.15: warning: possible forward-incompatibility.
automake-1.15: At least a source file is in a subdirectory, but the 'subdir-objects'
automake-1.15: automake option hasn't been enabled.  For now, the corresponding output
automake-1.15: object file(s) will be placed in the top-level directory.  However,
automake-1.15: this behaviour will change in future Automake versions: they will
automake-1.15: unconditionally cause object files to be placed in the same subdirectory
automake-1.15: of the corresponding sources.
automake-1.15: You are advised to start using 'subdir-objects' option throughout your
automake-1.15: project, to avoid future incompatibilities.

**Comment by c0ntrol** [comment]
Yes I have seen those warnings too but haven't got arround to fix them yet.

**Comment by flvi0** [comment]
I am working on this, while refactoring thirdparty libs into a "thirdparty" directory and updating the automake/autoconf stuff accordingly, see #8.
