### ISSUE TITLE
lvd  crop : parameter initialization

### ISSUE THREAD

**Issue by d-j-a-y** [c0ntrol/veejay#44]
Actually ( 2d582f264d75b04 ) lvd crop start with all parameter set at 0 and this behavior produce a blank output (all black). From my pov, playing live, this behavior it's not really interesting.

I think p1 and p3 should be initialized to sample width and height.

**Comment by c0ntrol** [comment]
There was a bug in loading user defined default values, you will need to remove $HOME/.livido/lvd_crop.so.cfg
