### ISSUE TITLE
veejay and reloaded crashes: FPE

### ISSUE THREAD

**Issue by zenny** [c0ntrol/veejay#46]
Veejay and reloaded crashes (FPE) on loading a samplelist.

Find attached bt of veejay-server. (Still cannot attache file, so I shall send it to @c0ntrol's email.

**Comment by c0ntrol** [comment]
<pre>
Program received signal SIGFPE, Arithmetic exception.
0x00007fffce1384a8 in ?? () from 
/usr/lib/x86_64-linux-gnu/libgavl.so.1
(gdb) bt
#0  0x00007fffce1384a8 in ?? () from 
/usr/lib/x86_64-linux-gnu/libgavl.so.1
#1  0x00007fffce138868 in gavl_video_frame_create () from 
/usr/lib/x86_64-linux-gnu/libgavl.so.1
#2  0x00007fffce94d834 in init_instance (my_instance=0x7fffb8884320) 
at lvd_scale0tilt.c:187
#3  0x00007ffff7874857 in livido_plug_init (plugin=0x913dfa0, w=720, 
h=576, base_fmt_=300, org_fmt_=13)
</pre>

**Comment by c0ntrol** [comment]
Seems like bug in gavl, maybe possible to add workarround if version is known

**Comment by zenny** [comment]
$ dpkg -l | grep ii | grep gavl
ii  libgavl-dev:amd64                           1.4.0-1
                                     amd64        low level audio and
video library - development files
ii  libgavl-doc                                 1.4.0-1
                                     all          low level audio and
video library - documentation files
ii  libgavl1:amd64                              1.4.0-1
                                     amd64        low level audio and
video library - runtime files

**Comment by d-j-a-y** [comment]
```
$ dpkg -l | grep ii | grep gavl
ii  libgavl1:amd64        1.4.0-1        amd64        low level audio and video library - runtime files
```

from my side, i did not have libavl-dev (nor doc) but same version (on same base platform)

**Comment by zenny** [comment]
>  i did not have libavl-dev (nor doc) but same version (on same base platform) and no SIGFPE

Do you mean the libgavl-dev:amd64 is causing the FPE?

**Comment by c0ntrol** [comment]
Please try updating the plugin sources; I have changed how it (lvd_scale0tilt) initializes.

**Comment by d-j-a-y** [comment]
@zenny 
>Do you mean the libgavl-dev:amd64 is causing the FPE?
humm i wouldn't say that' is't causing, but if you don't really nead libgavl-dev to devellop, maybe you can try uninstalling it... maybe

**Comment by c0ntrol** [comment]
Closing issue, should be resolved (lvd_scale0tilt initialization was changed)
