### ISSUE TITLE
reloaded - expose veejay functionality

### ISSUE THREAD

**Issue by c0ntrol** [c0ntrol/veejay#47]
* (80% done) generator (veejay -Z5) add parameter panel (currently exposed by stream color wheel) 
* video4linux capture device controls (common controls but veejay has all)
* expose sample information (frame number of mixing sample, loop count, sub render status, sub rendering global on/off )
* *optional* Fx list access by keyword instead of first letter only (or alternate solution to manage growing number of FX)
* ~~vloopback video writer on/off~~
* ~~sub render toggle button~~
* ~~parameter value hints~~

**Comment by d-j-a-y** [comment]
[WIP] Fx list access by keyword
