### ISSUE TITLE
Fx : Photoplay (timescreched mosaic) : add random mode

### ISSUE THREAD

**Issue by d-j-a-y** [c0ntrol/veejay#48]
on p2 / mode parameter, add random mode to select chessboard randomly.

**Comment by c0ntrol** [comment]
you mean every uneven square should be colored black ?

**Comment by d-j-a-y** [comment]
i mean, p2, give the opportunity to fill the grip from top-left / bottom-right .... but linearly .

in random mode, each coordinate of the grid selected by drawing lots .

**Comment by c0ntrol** [comment]
not really clear to me, diagonal fill ? every frame update, one additional small picture is added according to its matrix placement (see libvje/effects/common.c ; matrix_placement* functions)
If added there, as bonus other effects will have this feature as well

**Comment by d-j-a-y** [comment]
Well, quickly and nicely done ...  !
