### ISSUE TITLE
Reloaded> Enable/Disable all keyframes : empty callback

### ISSUE THREAD

**Issue by d-j-a-y** [c0ntrol/veejay#49]
The [on_curve_toggleglobal_toggled](https://github.com/c0ntrol/veejay/blob/4981799a6465f7f5e8e4ac59a2a98f911c1580dc/veejay-current/veejay-client/src/callback.c#L2474) is empty.

 * Deactivate button in reloaded ?
 * Write that function ?

**Comment by c0ntrol** [comment]
remove the button, there is no corresponding event in veejay for this

**Comment by d-j-a-y** [comment]
i have done it in the same commit that "toggle rendering mixing sources" request

**Comment by c0ntrol** [comment]
its commented out, it should be removed (glade parser does not always ignore comments)

**Comment by d-j-a-y** [comment]
fixed
