### ISSUE TITLE
Gentoo build against libav-11.3 failing

### ISSUE THREAD

**Issue by flvi0** [c0ntrol/veejay#5]
The pixel formats used by ffmpeg/libav are not recognized by the current libav version:
yuvconv.c: In function 'yuv_init_lib':
yuvconv.c:355:7: error: 'PIX_FMT_0BGR' undeclared (first use in this function)
  put( PIX_FMT_0BGR, IMG_ABGR32 );
...

In general, do we want to support libav in addition to ffmpeg? I have talked to the devs a while ago and their reason for forking was to get a cleaner codebase by removing lots of legacy/dead code from the project, which the ffmpeg maintainer continuously refused to do. I subsequently switched to using libav on my Gentoo system. The default choice on Gentoo, and on many other distros it seems has been to switch back to ffmpeg some time ago. Here is the rationale given by the Debian project, which lists mainly security concerns: https://wiki.debian.org/Debate/libav-provider/ffmpeg

Still I'd like to stick with libav for the time being. I will see if there's much effort in supporting both versions at once (I expected them to be compatible anyways). Maybe it's just a version issue. Which ffmpeg versions are you using to build veejay, and on which distribution(s)?

**Comment by d-j-a-y** [comment]
> Which ffmpeg versions are you using to build veejay, and on which distribution(s)?
From ubuntu 14.10 i build against ffmpeg release 2.6.x , see http://veejayhq.net/installing/ for step by step explanation.

**Comment by flvi0** [comment]
On Arch Linux I successfully build against ffmpeg-2.7.2.

**Comment by flvi0** [comment]
I checked against the ffmpeg/libav repositories and it seems the respective formats never got introduced to libav in the first place. I posted to the libav-api mailing list asking for advice on wether they might get added, why they are missing, and which alternative format could be used instead.

**Comment by flvi0** [comment]
Ok, libav definitely does not provide those formats, since they are considered redundant and basically express RGBA with alpha ignored (so the last byte does not need to be filled with 255). 

Does veejay in any way depend on the last byte being set as 0 or are the formats otherwise used in a special way? If the last byte is ignored anyway, it should be possible to just replace RGB0 with RGBA etc.  Additionaly, it seems that PIX_FMT_RGBA etc. are  present already in the earliest ffmpeg versions, so we could at once get rid of the #if LIBAVUTL_VERSION_MAJOR > 52.

If noone objects, I would make the according changes. @c0ntrol ?

**Comment by flvi0** [comment]
Looking at all occurences of the respective PIX_FMTs it seems it should not be a problem to replace them. They are only used to determine the stride size of 4 in all places I could find. I would propose to just remove them, and instead add ARGB, ABGR in addition to RGBA, BGRA which are present.

Anyways it seems that those formats never got used in the first place, since that would lead to disaster:
static  int		    ffmpeg_aclib[64];
is defined with a static size of 64, however in the current ffmpeg version PIX_FMT_BGR0 etc. have the values 295-298 as can be quickly verified by the following test program

#include <stdio.h>
#include <libavutil/pixfmt.h>

int main() {
	printf("%d\n", PIX_FMT_RGB0);
	printf("%d\n", PIX_FMT_BGR0);
	printf("%d\n", PIX_FMT_0RGB);
	printf("%d\n", PIX_FMT_0BGR);
}

The static array size should probably be
AV_PIX_FMT_NB,        ///< number of pixel formats...

Also, what's the rationale behind the put(a, b) macro?

**Comment by c0ntrol** [comment]
Thanks, I merged your pull request

For veejay, it should not matter if libav or ffmpeg. The parts of the
codebase veejay uses is identical in both libraries. It just a matter of
following up on them renaming stuff (hence the #ifdef nightmare)

See you,
