### ISSUE TITLE
Reloaded : Fx list access by keyword , not only by beginning letters

### ISSUE THREAD

**Issue by d-j-a-y** [c0ntrol/veejay#55]
Actually in the Fx list panel (tree_effectmixlist GtkTreeView) , fx can be founded by typing the first letter of the fx name. Start typing, and the first fx name beginning by the text you wrote will be hightlighted. Arrow key to select others.

Could be awesome this could work for any world composing the fx name , and even super awesome with extra keywords describing the kind of fx (category like : blur / mirror / color / wired / .... ?)

The treeview list could be filtered (has option? ) has we start typing to match only result.

**Comment by d-j-a-y** [comment]
https://bloerg.net/2012/10/23/sorted-and-filtered-tree-view.html

http://blog.borovsak.si/2009/05/gtktreemodel-and-filtering-4.html (last article of four)

**Comment by c0ntrol** [comment]
If you want, you can do this ? For me this is not such an important feature

**Comment by c0ntrol** [comment]
Also, since the FX list is so long (see #42) it maybe best to divide the FX into categories first

**Comment by c0ntrol** [comment]
Moving this to issue #47 (reloaded functionality)
