### ISSUE TITLE
sayVIMS : something broken ?

### ISSUE THREAD

**Issue by d-j-a-y** [c0ntrol/veejay#57]
i try the first example of the man page 
```
$ sayVIMS -h localhost -p 3490 255:;
I: Link: 0 connected with 127.0.0.1 on port 57735
I: Link: 0 connected with 127.0.0.1 on port 43232
 
 ^E: Invalid VIMS instruction 'V001D '
```
got that.... something broken doctor ?

**Comment by c0ntrol** [comment]
not reproducable, did you do a clean build before you encountered this issue? status mechanism changed one or two days ago which could explain this issue if you did not recompile sayVIMS
<pre>
D: VIMS (v) Message too small
D: Message content
D: msg [V000D255:;] (4 bytes) at position 0
 ^D: VIMS (v) - dropped message
E: Invalid VIMS instruction 'V000D255:;'
</pre>

**Comment by d-j-a-y** [comment]
still the same problem even for 017 event ... 
``` $ sayVIMS -h localhost -p 3490 017:; ```
i may do something wrong.

**Comment by c0ntrol** [comment]
the ';' might get interpreted by bash, and sayVIMS like that would start it in interactive mode (reading from stdin), try:
<pre>
sayVIMS -h localhost -p3490 -m "017:;"
</pre>

**Comment by d-j-a-y** [comment]
yep ! that's working now. I will do some change into sayVIMS man page because in bold, " character is not displayed !

So : Is it normal that take so much time ~1700 ms ?
```
#!/bin/bash

START_TIME=`echo $(($(date +%s%N)/1000000))`

sayVIMS -h localhost -p3490 -m "017:;"

END_TIME=`echo $(($(date +%s%N)/1000000))`
ELAPSED_TIME=$(($END_TIME - $START_TIME))

echo $ELAPSED_TIME
```

**Comment by d-j-a-y** [comment]
>So : Is it normal that take so much time ~1700 ms ?
because of connect and disconnect time i guess ?
for velocity... interactive mode !

**Comment by c0ntrol** [comment]
1700 ms is too long, sayVIMS should depend on veejay's frame period (so if rendering takes 2 seconds, sayVIMS will take 2 seconds as well)

This is with veejay -d and no FX ?

Also, for timing just issue 'wall' in front of sayVIMS for accurate measurement

**Comment by d-j-a-y** [comment]
>This is with veejay -d and no FX ?

i have redone the test with -d and it's quite the same result.

**Comment by c0ntrol** [comment]
what is the output from `wall sayVIMS -h localhost -p3490 -m "017:;"` ? 

i'll look at this tomorrow

**Comment by d-j-a-y** [comment]
```
$man wall

wall - write a message to all users
```
wall ???
