### ISSUE TITLE
FX : ascii art generation - libcaca ?

### ISSUE THREAD

**Issue by d-j-a-y** [c0ntrol/veejay#59]
What about a video2ascii filter ? 
Licaca is known to do it ...   _libcaca is a graphics library that outputs text instead of pixels_

https://github.com/cacalabs/libcaca

**Comment by flv0** [comment]
was thinking about this the other day. and i think yes, libcaca
would be the library of coice. libaa supports no color, and i
also think it's older / less maintained.

i had written a "to-console renderer plugin" for our virtual
reality library with libaa back when i was still in aachen, that
was fun.

so yeah, do it! :)

**Comment by c0ntrol** [comment]
It is all fine, as long as it is a LiViDO plugin so it does not add dependencies to the veejay project

Also consider that you may need to convert the resulting ASCII back into an image for further processing and display (you said filter)

Alternatively, if written as sink (just 1 input, no outputs), it could replace the SDL Video Window

For me priority goes to the other open issues :)

**Comment by d-j-a-y** [comment]
hummm not sure about LiViDO... but can contact easily the dev team.

**Comment by c0ntrol** [comment]
livido is simply veejay's plugin system, libcaca developers would not know about it.  A feature branch would only be needed if this should go into veejay core

**Comment by c0ntrol** [comment]
you can grab X-window and pipe it to vloopback device

ffmpeg -f x11grab -r 25 -s 720x576 -i :0.0+0,0 -vcodec rawvideo -pix_fmt yuv422p -f v4l2 /dev/video0

for specific window, see
http://www.lxtips.com/2011/07/single-window-screen-capture-script.html

this issue can be closed if nobody is going to implement it as a filter

**Comment by c0ntrol** [comment]
Removed minor label; libcaca is quite extensive on its feature set so it is all but a minor enchancement (many filters could be derived from it)

**Comment by c0ntrol** [comment]
Closing issue, fix all others first.

**Comment by flv0** [comment]
Aaww cmon don't be so hard ;) No fine there's plenty of other stuff to do first. Will also get more actively involved now. Btw I'm still idling all the time in #veejay on freenode so maybe join there people so we can have some  casual discussion and easier coordination of efforts. No need to, just reminding, I'm always there by now (hadn't been for a while after I announced the channel).

**Comment by c0ntrol** [comment]
Ok , let's keep it open :)

**Comment by c0ntrol** [comment]
Idling on freenode.net, #veejay - Will check every couple of hours for visitors :)

**Comment by flv0** [comment]
Hey, sorry I should have mentioned that I'm visiting my hometown this weekend, starting today. Will be there as long as I'm on my machine, but count on me to be there all the time beginning mid next week again, since I'm always on IRC anyways.

**Comment by c0ntrol** [comment]
plugin-packs/lvdasciiart (with aalib)

![ascii-0](https://user-images.githubusercontent.com/7851900/59866680-79391780-938c-11e9-9447-23a9f569b2a3.jpg)
![ascii-1](https://user-images.githubusercontent.com/7851900/59866681-79391780-938c-11e9-96e3-c3b1fefe8364.jpg)
![ascii-2](https://user-images.githubusercontent.com/7851900/59866682-79d1ae00-938c-11e9-9319-84692c653a18.jpg)
![ascii-3](https://user-images.githubusercontent.com/7851900/59866683-79d1ae00-938c-11e9-939d-c272d0212014.jpg)
![ascii-4](https://user-images.githubusercontent.com/7851900/59866684-79d1ae00-938c-11e9-80c9-59eb5174bb19.jpg)
![ascii-5](https://user-images.githubusercontent.com/7851900/59866686-7a6a4480-938c-11e9-857c-3e13890d8c38.jpg)
![ascii-6](https://user-images.githubusercontent.com/7851900/59866687-7a6a4480-938c-11e9-921b-53401cc4c058.jpg)
![ascii-7](https://user-images.githubusercontent.com/7851900/59866689-7a6a4480-938c-11e9-9ca6-5114d585a59b.jpg)
![ascii-8](https://user-images.githubusercontent.com/7851900/59866690-7b02db00-938c-11e9-9e36-7e815fcec48c.jpg)
![ascii-9](https://user-images.githubusercontent.com/7851900/59866691-7b02db00-938c-11e9-8678-8f62e8dd7c3a.jpg)

**Comment by d-j-a-y** [comment]
This effect give awesome result !!!!!

**Comment by c0ntrol** [comment]
yes! many possibilities there

also, i just added a new FX, Bloom
https://en.wikipedia.org/wiki/Bloom_(shader_effect)
