### ISSUE TITLE
refactor libstream/libsample into libvevosample

### ISSUE THREAD

**Issue by c0ntrol** [c0ntrol/veejay#60]
backport libvevosample from veejay-2.0 local repository

(1.6 release)

**Comment by flv0** [comment]
On 11/17/2015 10:29 PM, Niels wrote:
> veejay-2.0 local repository

huh? vj-2.0? can you elaborate on that?

**Comment by c0ntrol** [comment]
yes,sure! earlier this year,as an experiment I refactored libstream and libsample into libvevosample, which is a more modular structure on top of libvevo to provide a single API for sample based editing.
It provides various sources (v4l2,editlist,network, etc) and sinks (sdl, network, recording) as well as a dynamic namespace intended for event handling

Attached you will find some header files (in one long text file, since github wont let me attach .h files) that would give you a general idea
[header.txt](https://github.com/c0ntrol/veejay/files/38209/header.txt)

**Comment by c0ntrol** [comment]
prioritize this

**Comment by c0ntrol** [comment]
close issue, instead refactor vj-event.c vj_event_* methods and remove all occurences of SAMPLE_PLAYING and STREAM_PLAYING.  A parameter to each event needs to be added to indicate whether the event should be applied on stream or sample.
