### ISSUE TITLE
Reloaded : save / load project

### ISSUE THREAD

**Issue by d-j-a-y** [c0ntrol/veejay#61]
Has the two project will used _sample_000xx.edl_ there will be a problem.

could be the _sample_00001.edl_ be prefixed by the project name or something like that ?

**Comment by c0ntrol** [comment]
veejay currently always takes the current working directory, so if you start veejay in a new (empty) directory it will write the files there. There is no project configuration (yet) in veejay that would bundle all user configuration such as samplelists, actionfiles, midi configuration, editlists, videofiles, recorded files etc etc. So, this is actually an enhancement to both reloaded and veejay

**Comment by c0ntrol** [comment]
Issue #65 must be resolved before picking up this one

**Comment by c0ntrol** [comment]
close issue, no priority
