### ISSUE TITLE
sayVIMS : interactive mode behaviour bad messages

### ISSUE THREAD

**Issue by d-j-a-y** [c0ntrol/veejay#63]
After a baldy formated message ('xxx' , '017:' .... ) , well formated message doesn't work again (nota; message sent from reloaded still working)

Also, badly formated message sent in interactive mode, should output warning/error message like 'unknown VIMS command'

**Comment by c0ntrol** [comment]
sayVIMS doesnt really know what is valid VIMS message or not. The thing is, we do not want to wait for a reply to know if the command was valid

A badly formatted message currently breaks the connection, so in fact interactive sayVIMS should re-connect when connection is lost

**Comment by d-j-a-y** [comment]
>The thing is, we do not want to wait for a reply 

could eventually we wait in a thread ... 
>A badly formatted message currently breaks the connection (veejay will kill the client), so in fact interactive sayVIMS should re-connect when connection is lost

so we could not have to check everytime the connection , and re-connect when it's needed ?
maybe package could be lost during this time ?

Finally, if check connection (ping) is less time consuming let's do that only.

I could try to implement the solution you think the less worst.

**Comment by c0ntrol** [comment]
Perhaps it can wait in a thread, perhaps not but it will be complicated 

If sending fails, then you know the connection is gone and can reconnect, that would only need error handling in sayVIMS and a number of retries before giving up after a message; you would need to handle failed status reads and failed send/recv

veejay network i/o is blocking, changing it to non-blocking has high impact

A client is updated at each frame period, so VIMS event handler does not have/need any protection for concurrency (no locking). Messages that arrive after the frame period, are handled the next frame, iow messages are queued while playing a frame.

**Comment by c0ntrol** [comment]
<pre>
bash-4.2$ time sayVIMS -h localhost -p3490 -m "017:;" 

real    0m0.431s
user    0m0.366s
sys     0m0.030s
</pre>

**Comment by d-j-a-y** [comment]
first >
```
$ time sayVIMS -h localhost -p3490 -m "017:;" 
I: Link: 0 connected with 127.0.0.1 on port 49084
I: Link: 0 connected with 127.0.0.1 on port 21636

real	0m2.111s
user	0m1.564s
sys	0m0.044s
```
second >
```
$ time sayVIMS -h localhost -p3490 -m "017:;" 
I: Link: 0 connected with 127.0.0.1 on port 49596
I: Link: 0 connected with 127.0.0.1 on port 22148

real	0m1.596s
user	0m1.352s
sys	0m0.032s
```

**Comment by c0ntrol** [comment]
Can you identify where exactly the delay is ?
<pre>
 strace sayVIMS -h localhost -p3490 -m "017:;" 
</pre>
For accurate measurement, you would need to run the command several times and calculate average...

**Comment by d-j-a-y** [comment]
>Can you identify where exactly the delay is ?  strace sayVIMS -h localhost -p3490 -m "017:;" 

The output is a bit complicated for me. I will try to take time to explore that.
