### ISSUE TITLE
Refactor xml parsing

### ISSUE THREAD

**Issue by d-j-a-y** [c0ntrol/veejay#65]
> TODO use of #DEFINE for parser commons PARSESAMPLE_START() PARSESAMPLE_END()
https://github.com/d-j-a-y/veejay/blob/master/veejay-current/veejay-server/libsample/sampleadm.c#L2978

this could indeed be refactored into a generic utility for parsing tokens from xml. it will impact libstream, libsample, vj-event.c, vjkf.c and libvevo (and thus clean up a lot of things)
i would prefer functions for this, and not defines

also, only public (non static) functions should be documented (but this has no priority for me tho)

from vj-event.c:
<pre>
 #define __xml_cstr( buf, var , node, name )\
{\
if(var != NULL){\
veejay_strncpy(buf,var,strlen(var));\
xmlNewChild(node, NULL, (const xmlChar*) name, (const xmlChar*) buf );}\
}
</pre>

from vjkf.c:
<pre>
static   int    get_xml_int( xmlDocPtr doc, xmlNodePtr node )
{
        xmlChar *tmp = xmlNodeListGetString( doc, node->xmlChildrenNode, 1 );
        char *ch = UTF8toLAT1( tmp );
        int res = 0;
        if( ch )
        {
                res = atoi( ch );
                free(ch);
        }
        if(tmp)
                free(tmp);
        return res;
}

</pre>

**Comment by c0ntrol** [comment]
removed veejay label, everything is veejay

**Comment by c0ntrol** [comment]
refactored xml utility methods to libvjxml, rest is part of issue #60
