### ISSUE TITLE
Mixing sample looping behaviour 

### ISSUE THREAD

**Issue by d-j-a-y** [c0ntrol/veejay#66]
Clip2 is 2s, Clip1 is 1s.

Clip1 add effect normal overlay over mixing source Clip2.

Clip1 is in "Normal Loop" .
When Clip1 reach end, both Clip1 and Clip2 loop to begin (and so Clip2 duration is 1s and __not__ 2s). 
Is it normal ? 

I thought before mixed Clip2 loop was __not__ based on Clip1 loop

**Comment by c0ntrol** [comment]
Are you sure you have been mixing with Clip2 ?  I see expected behaviour when I mix the samples, iow. Clip1 needs several loops to play all of Clip2

I test this using a videofile of 30 frames, each frame prints a unique number (1,2,3,..30). Sending it to you now...

**Comment by c0ntrol** [comment]
P.S: Does Clip2 have a chain to render ? Behaviour is not (yet) verified for chain sub render

**Comment by d-j-a-y** [comment]
hummm ... look like it's doing the right job ! 

I do not understand how i had the feeling it was not working.

I close the question.

Thank's.
