### ISSUE TITLE
Update news section on website

### ISSUE THREAD

**Issue by flv0** [c0ntrol/veejay#7]
Was talking to a friend about veejay, he looked it up, first reaction "hmm no release since 2010". We should keep the news page up to date or remove it.

**Comment by d-j-a-y** [comment]
I'have send updates to veejayhq 
https://github.com/veejayhq/veejayhq/pull/5

;-)

**Comment by flvi0** [comment]
Ah! Great!
(now I'm watching veejayhq repo as well ;))

**Comment by c0ntrol** [comment]
Resolve #76 and #67 , then update website is next logical step
