### ISSUE TITLE
convenience libraries not automatically re-linked with libveejay after update

### ISSUE THREAD

**Issue by d-j-a-y** [c0ntrol/veejay#72]
Why doing changes under libvje i must "make clean" ?

**Comment by c0ntrol** [comment]
libvje is a convenience library that is embedded into libveejay.so. libveejay.so is build under veejay, so if you change libvje, libveejay.so needs to be rebuild as well. This is true for all convenience libraries in veejay (which is everything)

**Comment by d-j-a-y** [comment]
This mean that libvje it's not a real lib . ok.  But why i need "make clean"  ? why the build system doesn't rebuild / link what needed ?

**Comment by c0ntrol** [comment]
That I don't know. The build system does not see it has to relink the convenience libraries

**Comment by flv0** [comment]
I have noticed the problem as well at some point. Maybe they need to be added as explicit prerequisites of the respective make targets. I might look into this, however won't find the time quickly since I'm pretty busy right now.

**Comment by c0ntrol** [comment]
Meanwhile, as a short-cut, you can do
<pre>
rm veejay/liblavplayvj.lo && make install
</pre>

(or any other .lo file)

**Comment by c0ntrol** [comment]
putting this on the 1.5.59 release as optional
