### ISSUE TITLE
FX chain mixer

### ISSUE THREAD

**Issue by c0ntrol** [c0ntrol/veejay#73]
Already existing:
* chain fader (opacity fade beteen original frame and FX chain final frame)
* alpha map transition (greyscale transition map from original frame to FX rendered frame)

Adding:
* opacity fade between selected FX entry and FX chain final frame
* alpha map transition beteween selected FX entry and FX chain final frame
* opacity fade between selected FX entry subrendered chain and FX chain final frame
* alpha map transition between FX entry subrendered chain and FX chain final frame

Limit:
* Just one method per FX chain (no stacking)

Reloaded:
* add radio button group to set one of the source (=fx chain buffer) selection modes
* global alpha button toggles between opacity and alpha map transition

**Comment by c0ntrol** [comment]
done

**Comment by d-j-a-y** [comment]
05398e0c90d5fd81e

REGRESSION (?) : the chain mixer Vertical Slider (gtkvslider) is no more animated when using "Frad in/out FX Chain" buttons

**Comment by c0ntrol** [comment]
Yes
