### ISSUE TITLE
refactor libvje 

### ISSUE THREAD

**Issue by c0ntrol** [c0ntrol/veejay#78]
> refactor all function calls like
> 
> <pre>
> extern void radcor_apply( VJFrame *frame, int width, int height, int a, int b, int c, int alpha);
> </pre>
> 
> 
> to
> 
> <pre>
> extern void radcor_apply( VJFrame *frame, int a, int b, int c, int alpha);
> </pre>
> 
> 
> and use with/height values from VJFrame in FX (frame->width,frame->height)
> 
> impact:
> - libvje/internal.h (remove function definitions, replace for #include header file)
> - libvje/vj-effman.c (remove width,height parameters from function call)
> - libvje/effects/*.[c|h]
> - libvje/transitions/*.[c|h]
> 
> *\* **DONE** *\* ( #102 , #105 , #127 , #126 , #121 , #112 , #107 , #129 )

also, refactor FX that use static variables:
- move to FX private struct 
- allocate struct in _malloc() function, assign FX private data to pointer passed in function arguments
- implement prepare()
- save FX private data outside scope of stream/sample (data must be retained between sample switches)
- retrieve FX private data through instance ID (use libvevo for storage)

adapt:
- motion mapping
- subtract BG 
- calibration
- etc.

also, see issue #65, FX state should be saved to disk;
- (background) frame if any
- internal state

also, see issue #31, #36 
- alpha, alpha channels

also, typed parameters;
- color, coordinate, threshold, blend mode, operator, etc

also, generate xml metadata from FX descriptive information for UI generation, see issue #98

also, revive event factory for coupling with OSC (open sound control) and other message systems
for fine grained control and customization of running FX stack (use FX as building blocks for issue #36)
- impacts VIMS (vj-event.c) -> refactor this as well and pass in sample type instead of querying current playmode in function method
- oscevent.c
- oscfactory.c
- oscsend.c
- uifactory.c
- oscservit.c

also, embed libplugger 

also, revamp https://github.com/mvhenten/veejayhq/blob/master/content/page/livido-osc.md, digest livido ideas into new libvje

**Comment by c0ntrol** [comment]
Started

**Comment by d-j-a-y** [comment]
outch ... what a nice todolist ! ;-)

**Comment by d-j-a-y** [comment]
has we are in the subject.
* sound effect support
* linking between sound effects param and visual effects param by graph node (https://github.com/GNOME/graph-gtk /or https://github.com/grindhold/libgtkflow ? )

**Comment by c0ntrol** [comment]
* capacity of changing fx of any clip == sample editing, this not depending on libvje but on libsample and libstream (issue #60)
* sound effect support is not in scope of libvje but for libvevosample (issue #60)
* linking parameters is in scope of libvje (motionmapping already does it for some fx, but the linking is hard-wired)

**Comment by d-j-a-y** [comment]
Working on refactoring function call i found the case that the width & height of **f2** VJFrame is given by **f**  VJFrame.

For the "Future", can we presuppose that **f2** will always have the same size that **f** ? (i want to say yes... but just to confirm)

```
static	void	motiondetect2(VJFrame *f, VJFrame *f2, int threshold, water_t *w)
{
	uint8_t *bg = w->diff_img + (f->width * f->height);
	uint8_t *in = f2->data[0];
	if(!w->have_img)
	{
		softblur_apply( f2,f->width,f->height,0);  //// <----- HERE
		//	veejay_memcpy(bg, f2->data[0], f->width * f->height );	
		vj_frame_copy1( f2->data[0], bg, f->width * f->height );
		w->have_img = 1;
		return;
	}
```
https://github.com/c0ntrol/veejay/blob/master/veejay-current/veejay-server/libvje/effects/water.c#L327

**Comment by c0ntrol** [comment]
it is correct that both must be the same size, but it will be better to use f2->len for the vj_frame_copy1 function and similarly (for softblur_apply) and the other places in case this ever changes

**Comment by c0ntrol** [comment]
#183
