### ISSUE TITLE
Move third-party libs to dedicated subfolder

### ISSUE THREAD

**Issue by flvi0** [c0ntrol/veejay#8]
It is not easily visible from the source tree which of the libs below veejay-server are part of the project and which are external dependencies included in the source tree. While at it, the license information on the 3rd party libs should be made more explicit. My current guess is all seems to be part of veejay except libOSC, however README and CONTRIBUTORS file is empty.

**Comment by flvi0** [comment]
Opened pull request #9 for this, also fixes #4. I was not sure about libyuv since it seems to have been adapted for veejay, is that right? Also we could think about moving the libs belonging to veejay to a subfolder as well, what do you think?

**Comment by c0ntrol** [comment]
OK, accepted pull request #9 

Libyuv is part of veejay but it contains some routines that originate from other sources, mostly from xine and mplayer. Some parts of that library still uses aclib (ffmpeg_aclib array) which should be removed/refactored someday but when refactored, it should be tested if functional (it will break)

liblzo contains a wrapper arround mini LZO, so it is OK to move it to external folder

mjpegtools, libOSC are third party libraries but libOSC has been modified/fixed 

libhash is also external, its a part of kazlib

**Comment by c0ntrol** [comment]
Tested OK on Ubuntu 14.10 and Slackware 14
