### ISSUE TITLE
Unable to queue video frame 1

### ISSUE THREAD

**Issue by c0ntrol** [c0ntrol/veejay#82]
File: cercle1.avi (mjpeg/avi)

E: Unable to queue video frame 1

**Comment by c0ntrol** [comment]
E: Frame 1, pos 26400, len 27226
E: Frame 2, pos 70050, len 0
E: Frame 3, pos 70058, len 25415

**Comment by c0ntrol** [comment]
Close issue, cannot be fixed. Frame data is simply not there

**Comment by d-j-a-y** [comment]
* What is the particularity of this file ? 
* How to not reproduce this particularity to not have this error happen ?

**Comment by d-j-a-y** [comment]
VEEJAY_MSG_WARNING : Frame %d is not a full frame (its length is %d)

**Comment by c0ntrol** [comment]
Should also output 
 "Unable to queue video frame %ld"

Current implementation should skip queuing this frame for playback (if played back, you will see the previous played frame)
