### ISSUE TITLE
maybe a bug in the benchmark timer

### ISSUE THREAD

**Issue by d-j-a-y** [c0ntrol/veejay#85]
```
< I: Using SIMD glibc memset()
---
> I: Using SIMD MMX/MMX2/SSE optimized memset()
```
> may be a bug in the benchmark timer

Related to `$ veejay -v -A1` and `$veejay -v -A2` on laptop webcam and hauppauge live usb capture device

**Comment by c0ntrol** [comment]
If you start 1x veejay, does it always select the same memory copy method ?

**Comment by d-j-a-y** [comment]
(oups ... i mess the first one)... 


$ veejay -v 
[...] 
I: Using SIMD SSE optimized memcpy() (128) 
I: Using SIMD glibc memset() 
[...] 

$ veejay -v 
[...] 
I: Using SIMD MMX2 optimized memcpy() 
I: Using SIMD glibc memset() 
[...] 

$ veejay -v 
[...] 
I: Using SIMD SSE optimized memcpy() (128) 
I: Using SIMD glibc memset() 
[...] 

$ veejay -v 
[...] 
I: Using SIMD MMX/MMX2/SSE optimized memcpy() v1 
I: Using SIMD glibc memset() 
[...] 

$ veejay -v 
[...] 
I: Using SIMD SSE optimized memcpy() (128) 
I: Using SIMD glibc memset() 
[...] 

$ veejay -v 
[...] 
I: Using SIMD MMX2 optimized memcpy() 
I: Using SIMD MMX/MMX2/SSE optimized memset() 
[...] 

$ veejay -v 
[...] 
I: Using SIMD SSE optimized memcpy() (128) 
I: Using SIMD glibc memset() 


----- Mail original ----- 

De: "Niels" <notifications@github.com> 
À: "c0ntrol/veejay" <veejay@noreply.github.com> 
Cc: "d-j-a-y" <d.j.a.y@free.fr> 
Envoyé: Lundi 14 Mars 2016 19:21:47 
Objet: Re: [veejay] maybe a bug in the benchmark timer (#85) 


If you start 1x veejay, does it always select the same memory copy method ? 
— 
Reply to this email directly or view it on GitHub . 




-- 

--

--

**Comment by c0ntrol** [comment]
It is possible that they have nearly identical timing results, I have increased the buffer size to remedy this but it may not make a large enough difference, so additionally you can configure your preferred memcpy/memset method by setting

export VEEJAY_MEMCPY_METHOD=<memcpy method>
export VEEJAY_MEMSET_METHOD=<memset method>

if you use an invalid value, a list of supported methods is printed and the glibc method is selected
