### ISSUE TITLE
Themes need update 

### ISSUE THREAD

**Issue by d-j-a-y** [c0ntrol/veejay#88]
I have the nice and colorfull "fruitsalad" configured in ~/.veejay/theme/theme.config

```
$ reloaded -t
[...]
E: No such widget (togglebutton): 'kf_p15'
E: No such widget (togglebutton): 'kf_p14'
E: No such widget (togglebutton): 'kf_p13'
E: No such widget (togglebutton): 'kf_p12'
E: No such widget (togglebutton): 'kf_p11'
E: No such widget (togglebutton): 'kf_p10'
E: No such widget (togglebutton): 'kf_p9'
```

**Comment by c0ntrol** [comment]
The themes are only style changes, they do not add or remove widgets.
So, what .glade file is loaded by reloaded ? It should load gveejay.reloaded.glade and it should match the gveejay.reloaded.glade file from veejay-client/share

**Comment by d-j-a-y** [comment]
Yes you are right ... 
>So, what .glade file is loaded by reloaded ? 

will review that, and update the issue.

**Comment by d-j-a-y** [comment]
So, what .glade file is loaded by reloaded ?

/usr/share/reloaded/gveejay.reloaded.glade

```
diff /usr/share/reloaded/gveejay.reloaded.glade ~/Sources/veejay-git/veejay-current/veejay-client/share/gveejay.reloaded.glade

== NULL
```
In fact, 
```
E: No such widget (togglebutton): 'kf_p15'
E: No such widget (togglebutton): 'kf_p14'
E: No such widget (togglebutton): 'kf_p13'
E: No such widget (togglebutton): 'kf_p12'
E: No such widget (togglebutton): 'kf_p11'
E: No such widget (togglebutton): 'kf_p10'
E: No such widget (togglebutton): 'kf_p9'
```
happen **everytime** : 
* echo Default > ~/.veejay/themes
* echo fruitsalad > ~/.veejay/themes
* $reloaded -t
* $reloaded

**Comment by d-j-a-y** [comment]
Outch ... now.... never happen again.... wonderful and scaring ;-)

**Comment by c0ntrol** [comment]
Where is it beeing loaded from ? Perhaps it loads an old .glade file from a previous installation 
But if it does not happen anymore, issue can be closed :D

**Comment by d-j-a-y** [comment]
Still happen randomly ...

**Comment by c0ntrol** [comment]
What are exact steps to reproduce ?

**Comment by d-j-a-y** [comment]
No idea ...  nothing special.

**Comment by c0ntrol** [comment]
close issue, obsolete
