### ISSUE TITLE
Autoconnect not working

### ISSUE THREAD

**Issue by d-j-a-y** [c0ntrol/veejay#90]
`-a` option not working, even starting veejay with `-p4490` , even with the 3490 has default port path.

In fact the connection is done, but 
- the connection loop is'nt broke
- but the connection dialog is not closed
- the reloaded state is not updated.

**Comment by c0ntrol** [comment]
changed commandline usage help ; auto connect is only used in MT view.

**Comment by d-j-a-y** [comment]
i already have done a simple patch for -a == autoconnect ... 

did i push ?

**Comment by c0ntrol** [comment]
i saw that you changed the starting port from 4490 to 3490,

i did this change: 217f406c6357ff1dc780676e76ade2f253561896

maybe some confusion about auto-connect?

**Comment by d-j-a-y** [comment]
>maybe some confusion about auto-connect?
maybe... ?

take a look to this patch : https://github.com/d-j-a-y/veejay/commit/311740c1c96c6c5d494d7acbc98712e44b59431c who autoconnect reloaded at startup (not my nicest hack passing args by gui... but working)

**Comment by c0ntrol** [comment]
I think this patch would be OK, but it should be tested;
- disconnect veejay-server -> connection dialog should appear (if this works at all)
- disconnect track in MT and reconnect

**Comment by d-j-a-y** [comment]
>I think this patch would be OK, but it should be tested;

Tested a bit ... 
* closing veejay (ctrl-c), reloaded is still closed (nothing new)
* disconnect from MT and reconnect work has usual ... (not the same dialog box displayed)

**Comment by d-j-a-y** [comment]
[Missing] disconnect veejay-server -> connection dialog should appear (if this works at all)
