### ISSUE TITLE
Multiple fx parameters automation broken 

### ISSUE THREAD

**Issue by d-j-a-y** [c0ntrol/veejay#91]
* Add clip
* Add Fx with multiple parameters
* Automate p0
* Automate p1

:::::::::::::::::::::::::::::::::::::::
p0 is no more automated
:::::::::::::::::::::::::::::::::::::::

**Comment by d-j-a-y** [comment]
* New UI : "curve_toggleentry_param" (Fx stack / bottom right)
* New Vims : VIMS_SAMPLE_KF_STATUS_PARAM		=	142

**Comment by d-j-a-y** [comment]
* Add clip
* Add Fx with multiple parameters
* _FxAnim Panel_ : Select p0 and Automate p0
* Toggle _curve_toggleentry_param_ = [p0 is automated]
* _FxAnim Panel_ : Select p1 

:::::::::::::::::::::::::::::::::::::::
p0 is no more automated
:::::::::::::::::::::::::::::::::::::::

**Comment by c0ntrol** [comment]
is p1 automated ?

**Comment by c0ntrol** [comment]
should be fixed, can you test

**Comment by c0ntrol** [comment]
when fc parameter 'none' is toggled, the curve widget should be disabled but this is not the case

**Comment by d-j-a-y** [comment]
i want to say yep ! fixed.

Because of a new veejay functionality, the fx parameters anim "workflow" (using reloaded) have changed :
* From "Fx List" panel, Add a fx you like.
* From "Fx Chain" panel, toggle "keyframing for this fx chain entry"
* From "Fx Anim" panel, choose a parameter and toogle "keyframe animation for this param"
* From "Fx Anim" panel, draw the curve and hit [OK] "apply this keyframe"

**Comment by c0ntrol** [comment]
With 142, you can toggle whether a parameter is animated or not, with VIMS 145, you toggle whether parameter animation is enabled at all (global) 

For documentation, it would be great if you can put this in veejay-client/doc/FXAnim.txt in asciidoc format.
