### ISSUE TITLE
reloaded vertical parameter names gludges UI

### ISSUE THREAD

**Issue by c0ntrol** [c0ntrol/veejay#98]
Pull 97:

https://github.com/c0ntrol/veejay/pull/97

There are display problems:
* ~~Normal theme (no styling),  P10 to P15 labels no longer visible, P15 slider unusable (http://i.imgur.com/VHgyv8D.png)~~ Happens before-change as well
* Default theme, FX panel changes in size when different FX are added, the parameter name stretches the FX parameter panel (http://i.imgur.com/U3i0y65.png and http://i.imgur.com/Sm3yYH9.png)

Minor issues:
* Tooltip is the same as parameter-name label

**Comment by c0ntrol** [comment]
Disabling this functionality for now 
* put label on invisible
* do not update text in process_load_hints

**Comment by c0ntrol** [comment]
Suggestions:

* Pad label text / Limit text length (to keep FX panel from changing size) ?
* Change P12,P13,P14,P15 to horizontal sliders and make them visible when needed ? Solves issue with normal theme
* UI template for each FX (render GTK widgets according to meta description of FX, has additional to veejay)

**Comment by d-j-a-y** [comment]
>Default theme, FX panel changes in size when different FX are added, the parameter name stretches the FX parameter panel 

fixed by #101 

>UI template for each FX (render GTK widgets according to meta description of FX, has additional work to veejay-server libvje) instead of generic FX panel for all FX

Good idea! with nice selector widgets ?
Ex : https://code.google.com/archive/p/libprolooks/

**Comment by c0ntrol** [comment]
Actually, its not very hard to write GTK widgets (see gtktimeselection*, gtkknob*, gtkcolorsel*) but at this point, such a choice is still open :)

**Comment by c0ntrol** [comment]
close issue, continue refactor suggestions in #78
